---
# file: roles/common/tasks/main.yml

- name: yum update
  yum: name=* state=latest
  become: yes

- name: install vim
  yum: name=vim state=latest
  become: yes
- name: install tmux
  yum: name=tmux state=latest
  become: yes
